### ISSUE TITLE
Database for storing account information

### ISSUE THREAD

**Issue by CBM6** [AbirAahammed/E-card#24]
As a **user**, I need to able to **retrieval my account information**.
Estimates: 2 days
Time spent: 4 days (Asynchronous calls took a bit to set up properly)

**Comment by AbirAahammed** [comment]
We need to agree on a model of data before we move to database creation. @CBM6 , referring you as you created the issue, should talk about it in the next meeting.

**Comment by h-connor** [comment]
Moving issue to sprint 3.
While we do have a database that stores the login data, we will also have to expand this to contain the information of the users profile. Such as, phone#, description, etc..
