### ISSUE TITLE
Add firebase support for app data storage and authenticated login

### ISSUE THREAD

**Issue by AbirAahammed** [AbirAahammed/E-card#35]
- need to add the right dependency for firebase support 
- useful for firebase authentication
- useful for using firebase database

Time taken: ~5 days (including a full setup + research on the topic)

**Comment by AbirAahammed** [comment]
The following tasks are complete:

1. need to add the right dependency for firebase support
2. useful for firebase authentication

We need to finish the necessary task for using  firebase realtime db.

**Comment by hocky0414** [comment]
Progress: added firebase authentication(signup, login), will work on storage part for sprint 3
