### ISSUE TITLE
App wont open after closing android studio while a logged in session is active

### ISSUE THREAD

**Issue by ConnorGehman** [AbirAahammed/E-card#36]
Temporary fix: Uninstall the app on the emulator and run the app from android studio again.

Database connection buggy?

**Comment by ConnorGehman** [comment]
Another fix: Clearing the data for the app also allows you to open it again.
Settings->Apps->E-card->Storage->Clear Data

**Comment by hocky0414** [comment]
solved

**Comment by hocky0414** [comment]
Temporary fix: log out when onPause() called(switch apps, etc.)
TODO: need to re-login when user resumes the app.

**Comment by hocky0414** [comment]
fixed
