### ISSUE TITLE
Rating the profiles

### ISSUE THREAD

**Issue by hocky0414** [AbirAahammed/E-card#9]
As a **Customer**, I want to be able to **rate profiles** so I can review others and share my experience with a contractor or employee.
Estimate: 2 days
Time spent: TBD

**Comment by ConnorGehman** [comment]
This has been left uncompleted without a milestone because as the app progressed, we realized that with the method of viewing other people's cards we have created, it would be pointless to rate a profile/card.

**Comment by h-connor** [comment]
Revoked.
