### ISSUE TITLE
Update list of Service and list provinces in string.xml

### ISSUE THREAD

**Issue by AbirAahammed** [AbirAahammed/E-card#92]
- [Province list](https://github.com/AbirAahammed/E-card/blob/e587f6981a7c1ebaf6699a798ad42849572d8076/app/src/main/res/values/strings.xml#L56)
- [Service list](https://github.com/AbirAahammed/E-card/blob/e587f6981a7c1ebaf6699a798ad42849572d8076/app/src/main/res/values/strings.xml#L62)

Time Taken: 15 minutes

**Comment by ConnorGehman** [comment]
Added the provinces as well as some services.
